name = "AcousticAnalogies"
uuid = "e71b3392-1e0c-4536-b366-2bd1fce6fba0"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov> and contributors"]
version = "0.8.1"

[deps]
AcousticMetrics = "046f749b-9c1e-43ca-86bc-6902340f753e"
CCBlade = "e1828068-15df-11e9-03e4-ef195ea46fa4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
KinematicCoordinateTransformations = "730d3219-0a85-48f9-b699-9f31f8913d09"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
AcousticMetrics = "0.7.0"
CCBlade = "0.2.9"
CSV = "0.10.14"
DataFrames = "1.6.1"
FLOWMath = "0.4.1"
FillArrays = "1.11.0"
FlexiMaps = "0.1.18"
Format = "1.3.7"
JuliennedArrays = "0.4.0"
KinematicCoordinateTransformations = "0.4.1"
Meshes = "0.46.0, 0.47.9, 0.48.7, 0.49.5, 0.50.4, 0.51.22, 0.52.17, 0.53.4"
StaticArrays = "1.5.19"
Statistics = "1.9.0"
WriteVTK = "1.17.1"
julia = "1.9.1"
